version: "3.9"
services:
  hummingbot:
    container_name: hummingbot
    build: .
    restart: unless-stopped
    volumes:
      - ./conf:/app/conf
      - ./conf/connectors:/app/conf/connectors
      - ./conf/strategies:/app/conf/strategies
      - ./conf/controllers:/app/conf/controllers
      - ./conf/scripts:/app/conf/scripts
      - ./logs:/app/logs
      - ./data:/app/data
      - ./certs:/app/certs
      - ./scripts:/app/scripts
      - ./controllers:/app/controllers
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    tty: true
    stdin_open: true
    network_mode: host
    environment:
      - CONFIG_PASSWORD=${CONFIG_PASSWORD:-default}
    healthcheck:
      test: ["CMD", "pgrep", "-f", "hummingbot"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G

  gateway:
    container_name: gateway
    image: hummingbot/gateway:1.3.0
    restart: unless-stopped
    ports:
      - "15888:15888"
      - "8080:8080"
    volumes:
      - "./gateway_files/conf:/app/gateway/conf"
      - "./gateway_files/logs:/app/gateway/logs"
      - "./gateway_files/db:/app/gateway/db"
      - "./certs:/app/gateway/certs"
    environment:
      - GATEWAY_PASSPHRASE=${GATEWAY_PASSPHRASE:-default}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
